# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto import craw_pb2 as proto_dot_craw__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/craw_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CrawServiceStub(object):
    """定义服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrawWithURL = channel.unary_unary(
                '/craw.CrawService/CrawWithURL',
                request_serializer=proto_dot_craw__pb2.CrawWithURLRequest.SerializeToString,
                response_deserializer=proto_dot_craw__pb2.CrawWithURLResponse.FromString,
                _registered_method=True)
        self.T_KeepAlive = channel.unary_unary(
                '/craw.CrawService/T_KeepAlive',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class CrawServiceServicer(object):
    """定义服务
    """

    def CrawWithURL(self, request, context):
        """定义一个方法来计算两个整数的和
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def T_KeepAlive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CrawServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CrawWithURL': grpc.unary_unary_rpc_method_handler(
                    servicer.CrawWithURL,
                    request_deserializer=proto_dot_craw__pb2.CrawWithURLRequest.FromString,
                    response_serializer=proto_dot_craw__pb2.CrawWithURLResponse.SerializeToString,
            ),
            'T_KeepAlive': grpc.unary_unary_rpc_method_handler(
                    servicer.T_KeepAlive,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'craw.CrawService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('craw.CrawService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CrawService(object):
    """定义服务
    """

    @staticmethod
    def CrawWithURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/craw.CrawService/CrawWithURL',
            proto_dot_craw__pb2.CrawWithURLRequest.SerializeToString,
            proto_dot_craw__pb2.CrawWithURLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def T_KeepAlive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/craw.CrawService/T_KeepAlive',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
